### ISSUE TITLE
(shortfin) Cannot build with clang 19.1.3

### ISSUE THREAD

**Issue by AWoloszyn** [nod-ai/SHARK-Platform#497]
Builds work with clang 18.1.8 but fail in 19.1.3

```
In file included from SHARK-Platform/shortfin/src/shortfin/array/xtensor_bridge.cc:7:
In file included from SHARK-Platform/shortfin/src/shortfin/array/xtensor_bridge.h:13:
In file included from SHARK-Platform/shortfin/build/cmake/default/_deps/xtensor-src/include/xtensor/xadapt.hpp:20:
In file included from SHARK-Platform/shortfin/build/cmake/default/_deps/xtensor-src/include/xtensor/xarray.hpp:20:
In file included from SHARK-Platform/shortfin/build/cmake/default/_deps/xtensor-src/include/xtensor/xcontainer.hpp:25:
In file included from SHARK-Platform/shortfin/build/cmake/default/_deps/xtensor-src/include/xtensor/xmath.hpp:29:
In file included from SHARK-Platform/shortfin/build/cmake/default/_deps/xtensor-src/include/xtensor/xmanipulation.hpp:19:
In file included from SHARK-Platform/shortfin/build/cmake/default/_deps/xtensor-src/include/xtensor/xbuilder.hpp:31:
In file included from SHARK-Platform/shortfin/build/cmake/default/_deps/xtensor-src/include/xtensor/xgenerator.hpp:25:
SHARK-Platform/shortfin/build/cmake/default/_deps/xtensor-src/include/xtensor/xstrided_view.hpp:300:26: error: 'set_offset' is a protected member of 'xt::xstrided_view_base<xt::xstrided_view<const xt::xarray_adaptor<xt::xbuffer_adaptor<unsigned long *, xt::no_ownership, std::allocator<unsigned long>>, xt::layout_type::row_major, shortfin::array::InlinedDims<>> &, xt::svector<unsigned long>>>'
  300 |         using base_type::set_offset;
      |                          ^

```

Looks like the xtensor issue is https://github.com/xtensor-stack/xtensor/issues/2804
